services:
  - type: web
    name: ai-llm-playground
    runtime: docker
    plan: free 
    region: singapore 
    envVars:
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        sync: false
      - key: MASTER_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
      - key: OPENWEATHERMAP_API_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: GOOGLE_SEARCH_API_KEY
        sync: false
      - key: GOOGLE_CSE_ID
        sync: false
      - key: PINECONE_NAMESPACE
        sync: false
      - key: PINECONE_INDEX_NAME
        sync: false
      - key: PINECONE_API_KEY
        sync: false
    dockerContext: .
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/v1/health
